#!/usr/bin/python

import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

# from sme_hogar import application
# application.CONN_URI = 'mongodb://sme:sme@ds035997.mongolab.com:35997/smehogar'
# application.CONN_URI = None

# from database import DatabaseUsers
from priceprofor import myapplication
from utilities import connectiondetails as connectiondetailsutilities
from estadisticasgenericas import connectiondetails as connectiondetailsestadisticasgenericas
from dbpreciosesmanager import DBPreciosES
from omelinfosys.dbstudydatamanager import DBStudyData

''' SERVIDOR '''
# DatabaseUsers.connectiondetails['host'] = 'mongodb://sme:sme@ds035997.mongolab.com:35997/smehogar'
DBPreciosES.connectiondetails['host'] = 'mongodb://hmarrao:hmarrao@ds031117.mongolab.com:31117/mercadodiario'
DBStudyData.connectiondetails['host'] = 'mongodb://hmarrao:hmarrao@ds031117.mongolab.com:31117/mercadodiario'
connectiondetailsutilities['host'] = 'mongodb://hmarrao:hmarrao@ds031117.mongolab.com:31117/mercadodiario'
connectiondetailsestadisticasgenericas['host'] = 'mongodb://hmarrao:hmarrao@ds031117.mongolab.com:31117/mercadodiario'

application = myapplication
